#pragma once

#include <exception>
#include <iostream>
#include <memory>
#include <filesystem>
#include <string>
#include <list>
#include <stack>
#include <vector>
#include <map>
#include <optional>
#include <typeinfo>
#include <unordered_map>
#include <GL/glew.h>
#include <glm/glm.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <GLFW/glfw3.h>
#include <imgui.h>